---
title: "PrelimAnalysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


```{r}

nems <- read.table("OTU_log3.5.tab", header=T)
dim(nems)
head(nems)

View(nems)

levels(nems[is.na(nems$species_name_ok)==F,4])
nems[nems$species_name_ok=="Caenorhabditis elegans",]
which(nems$species_name_ok=="Caenorhabditis elegans")
nems[158,]

write.csv(nems, "nems1.csv")

nems3 <- read.table("OTU_log3.tab", header=T)
dim(nems3)
# Ok, X samples...

names(nems)

# Remove "Sample" from name
new <- sub("sample.","",names(nems))
names(nems) <- new
# Only take relevant data
nem2 <- nems[,c(15,31:533)]
# Transpose
tpose <- t(nem2)
names(tpose) <- tpose[1,]
tpose <- tpose[-1,]

new2 <- strsplit(row.names(tpose), c("_"))
b <- unlist(new2)
meta <- matrix(b, ncol=3,byrow=T)
#write.csv(tpose,"meta.csv")
cbind(meta,invert)
d <- read.csv("with_names.csv")

row.names(invert)
invert2 <- cbind(invert, row.names(invert))
Sample <- sub("sample.","",as.character(invert2[,330]))
invert3 <- cbind(invert2,Sample)
head(invert3)

nameys <- c(seq(1:329),"S","Sample")
colnames(invert3) <- nameys
invert3 <- as.data.frame(invert3)

sd <- read.csv("Sequenced_Samples_nem2018.csv")
head(sd)

easy <- sd[sd$Sample %in% invert3$Sample==T,]
sd[sd$Sample %in% invert3$Sample==F,5]

head(easy)
head(invert3)
names(invert3)
names(easy)
# This takes a little while
spes <- left_join(easy,invert3)
names(spes)[12:21] <- c("one","two","three","four","five","six","seven","eight","nine")

head(spes)
str(spes)
spes2 <- apply(spes[12:341],2,as.numeric)
spes3 <- cbind(spes[,1:11],spes2)

# Now I want to assign locations

plot(one~Species,data=spes3)
plot(two~Species,data=spes3)
plot(three~Species,data=spes3)
plot(four~Species, data=spes3)


spes3$Sample

LOCS <- as.data.frame(str_split_fixed(spes3$Sample, "_", n=3))
spes4 <- cbind(spes3,LOCS)
names(spes4)

for(i in 12:22){
  p <- ggplot(spes4,aes(x=Species,y=spes4[,i]))+
    geom_boxplot(aes(col=V1))
  print(p)
}

for(i in 23:33){
  p <- ggplot(spes4,aes(x=Species,y=spes4[,i]))+
    geom_boxplot(aes(col=V1))
  print(p)
}

for(i in 34:100){
  p <- ggplot(spes4,aes(x=Species,y=spes4[,i]))+
    geom_boxplot(aes(col=V1))
  print(p)
}

hist(rowSums(spes4[,12:340]))
maxes <- (apply(spes4[,12:340],1,max))
hist(maxes)
which(maxes<1000)




############ Start here
library(vegan)
comm_mat <- d[,6:334]
mm <- metaMDS(comm_mat)
stressplot(mm)

#Rarefy
min_depth <- min(colSums(comm_mat))
comm_rare <- as.data.frame(round(rrarefy(comm_mat, min_depth)))

log_comm_rare = log(comm_rare+1)
rank.totus <- rankindex(as.matrix(log_comm_rare), log_comm_rare, indices = c("bray", "euclid", "manhattan", "horn"), method = "spearman")
print(paste("The highest rank was given by the", names(sort(rank.totus, decreasing = TRUE)[1]), "method."))


otus_dist = as.matrix((vegdist(log_comm_rare, "manhattan")))
#perform NMDS
 NMDS = metaMDS(otus_dist)
stressplot(NMDS)
 
#build a data frame with NMDS coordinates and metadata
 MDS1 = NMDS$points[,1]
 MDS2 = NMDS$points[,2]
 NMDS = data.frame(MDS1 = MDS1, MDS2 = MDS2, Species = d$Species, Location = d$Location, Year=d$Year) 
 
head(NMDS)
eNMDS <- NMDS[NMDS$Species%in%c("Elephant","Buffalo","Impala","Warthog","Grevys Zebra","Plains Zebra"),]


ggplot(eNMDS, aes(x=MDS1, y=MDS2, col=Species)) +
 geom_point() +
 stat_ellipse() +
 theme_bw() +
 labs(title = "NMDS Plot")





#### Just do MPALA
summary(d$Species)
mpala_d <- d[d$Location=="MRC",]
summary(mpala_d$Species)

mpala_d <- mpala_d[mpala_d$Species%in%c("Buffalo","Cow","Dik-dik","Eland","Elephant","Giraffe","Grants Gazelle","Grevy's Zebra","Hartebeest","Impala","Plains zebra"),]

comm_mat <- mpala_d[,6:334]
#Rarefy
min_depth <- min(rowSums(comm_mat))
comm_rare <- as.data.frame(round(rrarefy(comm_mat, min_depth)))

log_comm_rare = log(comm_rare+1)
rank.totus <- rankindex(as.matrix(log_comm_rare), log_comm_rare, indices = c("bray", "euclid", "manhattan", "horn"), method = "spearman")
print(paste("The highest rank was given by the", names(sort(rank.totus, decreasing = TRUE)[1]), "method."))


otus_dist = as.matrix((vegdist(log_comm_rare, "manhattan")))
#perform NMDS
 NMDS = metaMDS(otus_dist,trymax=100)
stressplot(NMDS)
 
#build a data frame with NMDS coordinates and metadata
 MDS1 = NMDS$points[,1]
 MDS2 = NMDS$points[,2]
 NMDS2 = data.frame(MDS1 = MDS1, MDS2 = MDS2, Species = mpala_d$Species)
 NMDS2$Species <- droplevels(NMDS2$Species)
 
 NMDS2$Species <- factor(NMDS2$Species,levels(NMDS2$Species)[c(5,11,8,1,2,4,6,3,7,9,10)])
levels(NMDS2$Species)

head(NMDS2)

ggplot(NMDS2, aes(x=MDS1, y=MDS2, col=Species)) +
 geom_point() +
 stat_ellipse(level=0.50) +
 theme_bw() +
 labs(title = "NMDS Plot of Mpala Species")

adonis2(mpala_d[,6:334]~Species, data=mpala_d)





## All locations
lat_d <- d[d$Species%in%c("Elephant","Kudu","Warthog","Buffalo","Plains zebra","Impala"),]
lat_d$Species <- droplevels(lat_d$Species)
summary(lat_d$Species)


comm_lat <- lat_d[,6:334]
#Rarefy
min_depth <- min(rowSums(comm_lat))
comm_rare <- as.data.frame(round(rrarefy(comm_lat, min_depth)))

log_comm_rare = log(comm_rare+1)
rank.totus <- rankindex(as.matrix(log_comm_rare), log_comm_rare, indices = c("bray", "euclid", "manhattan", "horn"), method = "spearman")
print(paste("The highest rank was given by the", names(sort(rank.totus, decreasing = TRUE)[1]), "method."))


otus_dist = as.matrix((vegdist(log_comm_rare, "manhattan")))
#perform NMDS
 NMDS = metaMDS(otus_dist,trymax=100)
stressplot(NMDS)
 
#build a data frame with NMDS coordinates and metadata
 MDS1 = NMDS$points[,1]
 MDS2 = NMDS$points[,2]
 NMDS3 = data.frame(MDS1 = MDS1, MDS2 = MDS2, Species = lat_d$Species, Location= lat_d$Location)
NMDS3$Species <- factor(NMDS3$Species, levels(NMDS3$Species)[c(2,3,4,6,5,1)])
head(NMDS3)

ggplot(NMDS3, aes(x=MDS1, y=MDS2, col=Location, Type=Species)) +
 geom_point() +
 stat_ellipse(level=0.50) +
 theme_bw() +
 labs(title = "NMDS Plot of Species and Locations")


ggplot(NMDS3, aes(x=MDS1, y=MDS2, col=Location)) +
 geom_point() +
 stat_ellipse(level=0.50) +
 theme_bw() +
 labs(title = "NMDS Plot of Mpala Species")

adonis2(lat_d[,6:334]~Species+Location+Species*Location, data=lat_d)



### Now look at specific locations -- is there a lat gradient in diversity? NEED TO RAREFY BY READ DEPTH

lat_d$Location <- factor(lat_d$Location, levels(lat_d$Location)[c(5,9,7,6,3,8,2,4,1)])

lat_d$S <- specnumber(lat_d[,6:334])
plot(S~Species,data=lat_d)
plot(S~Location, data=lat_d)

library(lme4)
library(lmerTest)
library(MuMIn)

m <- lmer(logS~Latitude+I(Latitude^2)+(1|Species),data=lat_d)
m_null <- lmer(logS~(1|Species),data=lat_d)
summary(m)
plot(fitted(m)~lat_d$logS)
r.squaredGLMM(m,m_null)



lat_d$logS <- log(lat_d$S)
hist(lat_d$logS)

# Ok what if I replace these with latitudes???

lat_d$Latitude <- rep(0,length(lat_d$Location))
lat_d$Latitude[lat_d$Location=="MRC"] <- 0.29
lat_d$Latitude[lat_d$Location=="SER"] <- -2.40
lat_d$Latitude[lat_d$Location=="NYI"] <- -10.80
lat_d$Latitude[lat_d$Location=="NIA"] <- -12.48
lat_d$Latitude[lat_d$Location=="KAF"] <- -14.52
lat_d$Latitude[lat_d$Location=="PNG"] <- -18.78
lat_d$Latitude[lat_d$Location=="HWA"] <- -18.99
lat_d$Latitude[lat_d$Location=="KNP"] <- -23.95
lat_d$Latitude[lat_d$Location=="HIP"] <- -28.27

ggplot(lat_d, aes(x=Latitude,y=logS))+
  geom_smooth(method="gam",formula=y~poly(x,2))+
  geom_point()+
  facet_wrap(~Species)


```
